-- |
-- Module      : CSMT.Verify.CompletenessSpec
-- Description : Cross-check @csmt-verify@'s completeness verifier
-- Copyright   : (c) Paolo Veronelli, 2024
-- License     : Apache-2.0
--
-- The @csmt-verify@ sublibrary provides a pure verifier for
-- completeness proofs ('CSMT.Verify.verifyCompletenessProof').
-- This spec checks the round-trip (write side renders → wire bytes
-- → verifier bytes-in path) on real proofs generated by the
-- database-backed @generateProof@, plus the empty-leaves case
-- exercised by @POST /tx/oracle/end@ in the
-- @cardano-mpfs-offchain@ proof redesign (#243).
module CSMT.Verify.CompletenessSpec (spec) where

import CSMT
    ( Direction (..)
    , Standalone (StandaloneCSMTCol)
    )
import CSMT.Backend.Pure
    ( runPureTransaction
    )
import CSMT.Core.CBOR (renderCompletenessProof)
import CSMT.Hashes (Hash, hashHashing, mkHash, renderHash)
import CSMT.Interface (Hashing (..), Indirect (..), Key)
import CSMT.Proof.Completeness
    ( CompletenessProof (..)
    , collectValues
    , foldCompletenessProof
    , generateProof
    )
import CSMT.Test.Lib
    ( evalPureFromEmptyDB
    , hashCodecs
    , indirect
    , insertHashes
    , intHash
    , manyRandomPaths
    )
import CSMT.Verify qualified as Verify
import Data.Bits (xor)
import Data.ByteString (ByteString)
import Data.ByteString qualified as B
import Data.List (isPrefixOf, nub, sort)
import Data.Word (Word8)
import Database.KV.Transaction (query)
import Test.Hspec (Spec, describe, it, shouldBe, shouldSatisfy)
import Test.Hspec.QuickCheck (prop)
import Test.QuickCheck
    ( Gen
    , Property
    , arbitrary
    , checkCoverage
    , chooseInt
    , conjoin
    , counterexample
    , cover
    , elements
    , forAll
    , frequency
    , listOf
    , vectorOf
    , (===)
    )

-- | Generate a completeness proof against the empty prefix on a
-- random tree of hashes, returning the bytes the verifier would
-- see on the wire.
genTreeProof
    :: Gen
        ( ByteString -- root bytes
        , [Indirect Hash] -- sorted leaves
        , ByteString -- proof bytes
        )
genTreeProof = do
    ks <- manyRandomPaths
    let values = zipWith indirect ks (intHash <$> [1 ..])
        (mp, mr) = evalPureFromEmptyDB $ do
            insertHashes values
            mp' <-
                runPureTransaction hashCodecs
                    $ generateProof StandaloneCSMTCol [] []
            mr' <-
                runPureTransaction hashCodecs
                    $ query StandaloneCSMTCol []
            pure (mp', mr')
    case (mp, mr) of
        (Just proof, Just rootIndirect) ->
            pure
                ( renderHash (rootHash hashHashing rootIndirect)
                , sort values
                , renderCompletenessProof
                    (proof :: CompletenessProof Hash)
                )
        _ ->
            -- Fallback for the empty-tree case: render an empty proof
            -- against a dummy root. The properties below still bind
            -- the values to the proof.
            pure (B.replicate 32 0, [], B.empty)

genDeepPrefixTree :: Gen (Key, [Indirect Hash])
genDeepPrefixTree = do
    depth <- chooseInt (2, 6)
    prefixKey <- vectorOf depth (elements [L, R])
    let targetLeaves =
            [ prefixKey ++ [L, L]
            , prefixKey ++ [L, R]
            , prefixKey ++ [R, L]
            ]
        siblingLeaves =
            [ take i prefixKey
                ++ [opposite (prefixKey !! i)]
                ++ [L, R]
            | i <- [0 .. depth - 1]
            ]
        keys = targetLeaves <> siblingLeaves
    pure (prefixKey, zipWith indirect keys (intHash <$> [1 ..]))
  where
    opposite L = R
    opposite R = L

genRandomTreeAndPrefix :: Gen (Key, [Indirect Hash])
genRandomTreeAndPrefix = do
    keyCount <- chooseInt (16, 64)
    keys0 <- prefixFree . nub <$> vectorOf (keyCount * 4) genRandomKey
    let keys = take keyCount keys0
    if length keys < 8
        then genRandomTreeAndPrefix
        else do
            targetKey <- elements keys
            prefixLen <-
                frequency
                    [ (1, pure 0)
                    , (3, chooseInt (0, length targetKey))
                    , (6, chooseInt (min 2 (length targetKey), length targetKey))
                    ]
            let prefixKey = take prefixLen targetKey
            pure (prefixKey, zipWith indirect keys (intHash <$> [1 ..]))
  where
    genRandomKey :: Gen Key
    genRandomKey = do
        keyLen <- chooseInt (6, 16)
        vectorOf keyLen (elements [L, R])

    prefixFree :: [Key] -> [Key]
    prefixFree = foldr insertIfCompatible []
      where
        insertIfCompatible key keys
            | all (compatible key) keys = key : keys
            | otherwise = keys

        compatible a b =
            not (a `isPrefixOf` b || b `isPrefixOf` a)

genBS :: Gen ByteString
genBS = B.pack <$> listOf (arbitrary :: Gen Word8)

verifiesCompletenessRoundTrip
    :: Key -> [Indirect Hash] -> Property
verifiesCompletenessRoundTrip prefixKey values =
    let expectedLeaves =
            sort
                [ leaf
                | leaf@Indirect{jump} <- values
                , prefixKey `isPrefixOf` jump
                ]
        (mp, mr, collected) = evalPureFromEmptyDB $ do
            insertHashes values
            proof <-
                runPureTransaction hashCodecs
                    $ generateProof
                        StandaloneCSMTCol
                        []
                        prefixKey
            rootI <-
                runPureTransaction hashCodecs
                    $ query StandaloneCSMTCol []
            collectedLeaves <-
                runPureTransaction hashCodecs
                    $ collectValues
                        StandaloneCSMTCol
                        []
                        prefixKey
            pure
                ( proof :: Maybe (CompletenessProof Hash)
                , rootI
                , collectedLeaves
                )
    in  case (mp, mr) of
            (Just proof@CompletenessWitness{cpInclusionSteps}, Just rootIndirect) ->
                let trustedRoot = rootHash hashHashing rootIndirect
                    rootBs = renderHash trustedRoot
                    proofBs = renderCompletenessProof proof
                    sortedCollected = sort collected
                    stepCount = length cpInclusionSteps
                in  cover
                        30
                        (stepCount >= 2)
                        "deep (>=2 inclusion steps)"
                        $ counterexample
                            ( "prefix="
                                <> show prefixKey
                                <> ", inclusion steps="
                                <> show stepCount
                            )
                        $ conjoin
                            [ sortedCollected === expectedLeaves
                            , foldCompletenessProof
                                hashHashing
                                trustedRoot
                                prefixKey
                                sortedCollected
                                proof
                                === Just trustedRoot
                            , Verify.verifyCompletenessProof
                                rootBs
                                prefixKey
                                sortedCollected
                                proofBs
                                === True
                            ]
            (Just CompletenessEmpty{}, _) ->
                counterexample
                    "existing prefix unexpectedly produced an empty proof"
                    False
            _ ->
                counterexample
                    "expected populated proof + root for existing prefix"
                    False

spec :: Spec
spec = describe "csmt-verify completeness" $ do
    prop "round-trips real proofs and verifies under matching root"
        $ forAll genTreeProof
        $ \(rootBs, values, proofBs) ->
            -- Empty trees are skipped: the fallback produces empty
            -- bytes that legitimately fail to parse.
            B.null proofBs
                || Verify.verifyCompletenessProof
                    rootBs
                    []
                    values
                    proofBs

    prop "rejects a tampered root"
        $ forAll genTreeProof
        $ \(rootBs, values, proofBs) ->
            let badRoot = B.map (`xor` 0xff) rootBs
            in  B.null proofBs
                    || not
                        ( Verify.verifyCompletenessProof
                            badRoot
                            []
                            values
                            proofBs
                        )

    prop "rejects garbage proof bytes"
        $ forAll ((,) <$> vectorOf 32 arbitrary <*> genBS)
        $ \(rootBs, garbage) ->
            Verify.verifyCompletenessProof
                (B.pack rootBs)
                []
                []
                garbage
                === False

    prop "round-trips populated deep-prefix proofs"
        $ forAll genDeepPrefixTree
        $ \(prefixKey, values) -> do
            let expectedLeaves =
                    sort
                        [ leaf
                        | leaf@Indirect{jump} <- values
                        , prefixKey `isPrefixOf` jump
                        ]
                (mp, mr, collected) = evalPureFromEmptyDB $ do
                    insertHashes values
                    proof <-
                        runPureTransaction hashCodecs
                            $ generateProof
                                StandaloneCSMTCol
                                []
                                prefixKey
                    rootI <-
                        runPureTransaction hashCodecs
                            $ query StandaloneCSMTCol []
                    collectedLeaves <-
                        runPureTransaction hashCodecs
                            $ collectValues
                                StandaloneCSMTCol
                                []
                                prefixKey
                    pure
                        ( proof :: Maybe (CompletenessProof Hash)
                        , rootI
                        , collectedLeaves
                        )
            sort collected `shouldBe` expectedLeaves
            case (mp, mr) of
                ( Just proof@CompletenessWitness{cpInclusionSteps}
                    , Just rootIndirect
                    ) -> do
                        cpInclusionSteps `shouldSatisfy` \steps ->
                            length steps >= 2
                        let trustedRoot =
                                rootHash hashHashing rootIndirect
                            rootBs = renderHash trustedRoot
                            proofBs = renderCompletenessProof proof
                        foldCompletenessProof
                            hashHashing
                            trustedRoot
                            prefixKey
                            (sort collected)
                            proof
                            `shouldBe` Just trustedRoot
                        Verify.verifyCompletenessProof
                            rootBs
                            prefixKey
                            (sort collected)
                            proofBs
                            `shouldBe` True
                _ -> error "expected populated proof + root"

    prop "round-trips arbitrary tree + arbitrary existing prefix"
        $ checkCoverage
        $ forAll genRandomTreeAndPrefix
        $ uncurry verifiesCompletenessRoundTrip

    it "the wire format round-trips a hand-built proof" $ do
        -- Decoder/encoder symmetry on an already-known proof so we
        -- catch CBOR layout drift even when no tree is involved.
        let values =
                [ indirect [L, L, L, L] (mkHash "leaf-1")
                , indirect [R, R, R, R] (mkHash "leaf-2")
                ]
            (mp, _) = evalPureFromEmptyDB $ do
                insertHashes values
                mp' <-
                    runPureTransaction hashCodecs
                        $ generateProof StandaloneCSMTCol [] []
                mr' <-
                    runPureTransaction hashCodecs
                        $ query StandaloneCSMTCol []
                pure (mp' :: Maybe (CompletenessProof Hash), mr')
        case mp of
            Just proof ->
                let bs = renderCompletenessProof proof
                in  Verify.parseCompletenessProof bs `shouldBe` Just proof
            Nothing -> error "expected a proof"

    -- See https://github.com/lambdasistemi/haskell-mts/issues/157.
    -- The verifier's contract is "leaf jumps are absolute (within
    -- the column) — they start with @prefixKey@". Two cases must
    -- agree: leaves built manually from KV-row bytes (the
    -- cardano-mpfs-offchain consumer's natural form) and leaves
    -- returned by 'collectValues' (now also absolute).
    describe "non-empty prefix populated case (issue #157)" $ do
        let prefixKey :: [Direction]
            prefixKey = [L, R, L, R]
            -- Two leaves under the prefix; absolute keys of length
            -- 8 (4 bits prefix + 4 bits suffix).
            leafKeyA, leafKeyB :: [Direction]
            leafKeyA = prefixKey ++ [L, L, L, L]
            leafKeyB = prefixKey ++ [R, R, R, R]
            valA = mkHash "leaf-A"
            valB = mkHash "leaf-B"
            absoluteLeaves =
                [ indirect leafKeyA valA
                , indirect leafKeyB valB
                ]
            (mp, mr, collectedAbs) = evalPureFromEmptyDB $ do
                insertHashes absoluteLeaves
                proof <-
                    runPureTransaction hashCodecs
                        $ generateProof
                            StandaloneCSMTCol
                            []
                            prefixKey
                rootI <-
                    runPureTransaction hashCodecs
                        $ query StandaloneCSMTCol []
                collected <-
                    runPureTransaction hashCodecs
                        $ collectValues
                            StandaloneCSMTCol
                            []
                            prefixKey
                pure
                    ( proof :: Maybe (CompletenessProof Hash)
                    , rootI
                    , collected
                    )

        it "verifies with collectValues output (absolute jumps)" $ do
            case (mp, mr) of
                (Just proof, Just rootI) -> do
                    let rootBs =
                            renderHash (rootHash hashHashing rootI)
                        proofBs = renderCompletenessProof proof
                    Verify.verifyCompletenessProof
                        rootBs
                        prefixKey
                        (sort collectedAbs)
                        proofBs
                        `shouldBe` True
                _ -> error "expected proof + root"

        it "verifies with consumer-built absolute-key leaves" $ do
            case (mp, mr) of
                (Just proof, Just rootI) -> do
                    let rootBs =
                            renderHash (rootHash hashHashing rootI)
                        proofBs = renderCompletenessProof proof
                    Verify.verifyCompletenessProof
                        rootBs
                        prefixKey
                        (sort absoluteLeaves)
                        proofBs
                        `shouldBe` True
                _ -> error "expected proof + root"

        it "rejects leaves whose jumps don't start with the prefix"
            $ case (mp, mr) of
                (Just proof, Just rootI) -> do
                    let rootBs =
                            renderHash (rootHash hashHashing rootI)
                        proofBs = renderCompletenessProof proof
                        -- Strip the prefix bits — these are NOT
                        -- absolute, so the verifier must reject.
                        relativeLeaves =
                            [ indirect [L, L, L, L] valA
                            , indirect [R, R, R, R] valB
                            ]
                    Verify.verifyCompletenessProof
                        rootBs
                        prefixKey
                        (sort relativeLeaves)
                        proofBs
                        `shouldBe` False
                _ -> error "expected proof + root"

    describe "empty-prefix (absent prefix)" $ do
        -- A populated tree with a single anchor under [R,R,R,R];
        -- the prefix [L,L,L,L,...] therefore has no leaves and
        -- generateProof produces a CompletenessEmpty.
        let absent :: [Direction]
            absent = [L, L, L, L, L, L, L, L]
            anchor = indirect [R, R, R, R] (mkHash "anchor")
            (mp, mr) = evalPureFromEmptyDB $ do
                insertHashes [anchor]
                mp' <-
                    runPureTransaction hashCodecs
                        $ generateProof StandaloneCSMTCol [] absent
                mr' <-
                    runPureTransaction hashCodecs
                        $ query StandaloneCSMTCol []
                pure
                    ( mp' :: Maybe (CompletenessProof Hash)
                    , mr'
                    )
            withProof
                :: ( ByteString
                     -> [Indirect Hash]
                     -> ByteString
                     -> Bool
                   )
                -> IO ()
            withProof k = case (mp, mr) of
                (Just proof, Just rootIndirect) ->
                    let rootBs =
                            renderHash
                                (rootHash hashHashing rootIndirect)
                        proofBs = renderCompletenessProof proof
                    in  k rootBs [] proofBs `shouldBe` True
                _ -> error "expected proof + root"

        it "verifies under the matching root"
            $ withProof
            $ \rootBs leaves proofBs ->
                Verify.verifyCompletenessProof
                    rootBs
                    absent
                    leaves
                    proofBs

        it "rejects when the verifier supplies a different prefix"
            $ case (mp, mr) of
                (Just proof, Just rootIndirect) -> do
                    let rootBs =
                            renderHash
                                (rootHash hashHashing rootIndirect)
                        proofBs = renderCompletenessProof proof
                    Verify.verifyCompletenessProof
                        rootBs
                        ([R, R, R, R] :: [Direction])
                        []
                        proofBs
                        `shouldBe` False
                _ -> error "expected proof + root"

        it "rejects when leaves are non-empty"
            $ case (mp, mr) of
                (Just proof, Just rootIndirect) -> do
                    let rootBs =
                            renderHash
                                (rootHash hashHashing rootIndirect)
                        proofBs = renderCompletenessProof proof
                    Verify.verifyCompletenessProof
                        rootBs
                        absent
                        [anchor]
                        proofBs
                        `shouldBe` False
                _ -> error "expected proof + root"

        it "rejects a tampered root"
            $ case (mp, mr) of
                (Just proof, Just rootIndirect) -> do
                    let rootBs =
                            renderHash
                                (rootHash hashHashing rootIndirect)
                        badRoot = B.map (`xor` 0xff) rootBs
                        proofBs = renderCompletenessProof proof
                    Verify.verifyCompletenessProof
                        badRoot
                        absent
                        []
                        proofBs
                        `shouldBe` False
                _ -> error "expected proof + root"
